### ISSUE TITLE
White list some ranges of IP

### ISSUE THREAD

**Issue by Fratt** [PascalMinder/geoblock#24]
Hello,

I would like to white-list some ranges of IP Address in a country that's normally blocked.

Is this currently possible ?

Thanks a lot

**Comment by Fratt** [comment]
If this can help someone else, I found a "workaround".
You need to have `allowLocalRequests`set to `true`.
Edit `geoblock.go` and add the range in the `cidr` array of the method `initPrivateIPBlocks`

**Comment by PascalMinder** [comment]
I haven't thought about it yet, since I do not need it. But it might be an interesting idea. I look into it.

**Comment by Olen** [comment]
This would reallly be a great enhancement.  I have quite a few services that I only want to be available from specific regions, but that might also need e.g. some kind of remote monitoring tool that is hosted in a different country, without opening for all traffic from that country.

**Comment by PascalMinder** [comment]
Hi, sorry for the late answer. I’ll look into it as soon as I have some time at my hand.

**Comment by PascalMinder** [comment]
I have added a first draft to allow defining specific IP addresses which should always be allowed. What do you think?

**Comment by Olen** [comment]
Looks great.  
The official "ipWhiteList" plugin also allows for prefixes and IPv6:
```
tcp:
  middlewares:
    olen-net:
      ipWhiteList:
        sourceRange: 
          - "123.234.50.66/32"               # Home
          - "2a00:00c0:2:3::567:8001/128"  # Server
          - "178.90.234.0/24"             # Work
```

Does this work with your code as well?

**Comment by PascalMinder** [comment]
With my last commit, this should work.

**Comment by Olen** [comment]
Looks great.  Will try to test it as soon as possible.

**Comment by PascalMinder** [comment]
Fixed by f923e4e318124adfca739a2b1168306bcc9a9da5

**Comment by Fratt** [comment]
Thank you very much !

You forgot to add it here though : https://github.com/PascalMinder/geoblock/blob/main/geoblock.go#L122
(not a big deal ;-)
